apiVersion: batch/v1
kind: CronJob
metadata:
  name: patch-istio-configmap
  namespace: istio-system
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: sa-patch-istio-configmap
          containers:
          - name: patch
            image: markszabo/istio-crosscluster-workaround-for-eks
            imagePullPolicy: IfNotPresent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: role-patch-istio-configmap
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs:
  - 'patch'
  - 'get'
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - 'list' 
  - 'get'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-patch-istio-configmap
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: sa-patch-istio-configmap
  namespace: istio-system
roleRef:
  kind: Role
  name: role-patch-istio-configmap
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-patch-istio-configmap
  namespace: istio-system
